name: maizeplant
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_database: ^11.0.0
  pdf: ^3.8.4
  open_file: ^3.3.2
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/ml/model.tflite
    - lib/ml/labels.txt
    - assets/cover.png
    - assets/cover_2.png
    - assets/login.png
    - assets/mango.png
    - assets/sign_up.png
    - assets/cover4.png
    - assets/cover3.png
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf