// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB9puhdBnBuAPWoAvm6A_p29TLsn3Lehg',
    appId: '1:112799042632:web:d3c6f086621b376023dc7d',
    messagingSenderId: '112799042632',
    projectId: 'maize-plant-e1ae0',
    authDomain: 'maize-plant-e1ae0.firebaseapp.com',
    storageBucket: 'maize-plant-e1ae0.firebasestorage.app',
    measurementId: 'G-CCV5ZV94KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6lT1Gs26gyQXLqxzONUIQ4Qca4lACkS0',
    appId: '1:112799042632:android:8ae6b9c2e0fb052323dc7d',
    messagingSenderId: '112799042632',
    projectId: 'maize-plant-e1ae0',
    storageBucket: 'maize-plant-e1ae0.firebasestorage.app',
  );

}